import React from "react";
import styles from "@/styles/login.module.css"

type Props = {
    children: React.ReactNode
}

export const metadata = {
    title: 'Login 블로그',
    description: 'Generated by create next app',
}
export default function RootLayout(props: Props) {
    return (
        <div className={styles.background}>
            {props.children}
        </div>
    )
}
